// Auto-generated by scripts/scrape-legacy.mjs — do not edit by hand.

export type Article = {
  id: number;
  slug: string;
  title: string;
  dateISO: string;
  paragraphs: string[];
  image?: string;
};

export const articles: Article[] = [
  {
    "id": 51,
    "slug": "bingo-bingo",
    "title": "Bingo bingo",
    "dateISO": "2014-10-27",
    "paragraphs": [
      "Þá er komið að því!",
      "Við höldum Bingó, fimmtudaginn 30. október kl.19:30 í sal Sjálfsbjargar að",
      "Hátúni 12, Reykjavík (gengið inn sunnanmegin).",
      "Til sölu verður kaffi og meðlæti í hléi á sanngjörnu verði. Flottir vinningar.",
      "Athugið að ekki er hægt að taka við kortum og því þarf að vera með peninga.",
      "Og munum að það er alltaf gaman þegar Djúpmenn koma saman!"
    ]
  },
  {
    "id": 50,
    "slug": "dagskra-djupmannamots-2014",
    "title": "Dagskrá Djúpmannamóts 2014",
    "dateISO": "2014-06-25",
    "paragraphs": [],
    "image": "/articles/mot-2014.jpg"
  },
  {
    "id": 46,
    "slug": "vorkaffi-2014",
    "title": "Vorkaffi 2014",
    "dateISO": "2014-05-08",
    "paragraphs": [
      "Vorkaffi Djúpmanna verður haldið næstkomandi laugardag, 10. maí í sal Sjálfsbjargar að Hátúni 12, Reykjavík (gengið inn sunnanmegin).",
      "Boðið verður upp á kaffi og kökur gegn vægu verði.",
      "Kökur á 250kr",
      "Kaffi á 250kr",
      "Gos á 250kr",
      "Athugið að við getum ekki tekið við kortum og þurfa því allir að mæta með pening.",
      "Við hlökkum til að sjá sem ykkkur!"
    ]
  },
  {
    "id": 45,
    "slug": "adalfundur-2014",
    "title": "Aðalfundur 2014",
    "dateISO": "2014-03-27",
    "paragraphs": [
      "Aðalfundur Félags Djúpmanna",
      "Fimmtudaginn 20. mars 2014, klukkan 20:00",
      "Stungið upp á Halldóri Halldórssyni sem fundarstjóra og var það samþykkt samhljóða.",
      "Fundarstjóri þakkar traustið og fagnar félagsskapnum um leið og hann hrósar formanni og því að félagið sé að lifna við og æskir persónulegrar inngöngu í félagið.",
      "Stungið var upp á Ástu Dís Guðjónsdóttur sem fundarritara og var það samþykkt samhljóða.",
      "Fundarstjóri kynnir næsta dagskrárlið sem er kynning á skýrslu stjórnar.",
      "Jórunn formaður félagsins kynnir skýrslu stjórnar sem sjá má hér að neðan.",
      "Fundarstjóri kynnir Daníel gjaldkera sem fer yfir og útskýrir rekstrarreikning félagsins og útskýrir tekjur og gjöld á tímabilinu en þess má geta að félagið á enn land við Galtarhrygg með tveimur húsum á og er það eina eign félagsins.",
      "Reikningar síðan bornir upp til samþykktar og samþykktir samhljóða.",
      "Fyrirspurn kom um húsin tvö og kom fram að þetta væru frekar svokallaðir vegamannakofar en sumarhús þó eru gistimöguleikar fyrir 4-5 á staðnum.",
      "Félagsgjöld voru rædd og ákveðin óbreytt áfram 3.000.- kr. á ári.",
      "Næsti dagskrárliður eru kosningar:",
      "Núverandi formaður gefur kost á sér til áframhaldandi starfa, ekki kom fram mótframboð og Jórunn er því réttkjörinn formaður félagsins. Daníel Helgason gefur kost á sér til áframhaldandi starfa sem gjaldkeri og þar sem ekki kom fram mótframboð þá er hann réttkjörinn gjaldkeri. Það á einnig við um Einar Kjartansson en Hjörtur Aðalsteinsson gefur ekki kost á sér áfram enda hefur hann setið óslitið í stjórn í 16 ár og kunnum við honum kærar þakkir fyrir. Dagný Rós Stefánsdóttir gefur ekki kost á sér í stjórn en er til í að koma í varamann og kunnum við henni góðar þakkir fyrir það.",
      "Kjósa þarf til stjórnar og er óskað framboða úr sal. Eftirfarandi gáfu kost á sér:",
      "Reynir Snædal Magnússon frá Hallsstöðum og Halldór Jónsson frá Laugarási og voru þeir kosnir samhljóða.",
      "Kjósa þarf varamenn til stjórnar og er óskað framboða úr sal: Eftirfarandi gáfu kost á sér: Jóna S. Marvins, Dagný Rós Stefánsdóttir og Guðrún Karlsdóttir og voru þær samþykkta samhljóða.",
      "Skoðunarmenn reikninga: Magnea Guðmundardóttir og Ásdís Samúelsdóttir.",
      "Önnur mál:",
      "Formaður minnir á Djúpmannamót í sumar með dansiballi og hvetur fólk til að bóka gistingu og fjölmenna á svæðið.",
      "Fyrirspurn um Álfhól og hvort til standi að gera hann upp, Daníel svarar að verið sé að skoða kostnað og hugsanlega verði farið í framkvæmdir í vor þegar snjóalög leyfa.",
      "Hvatning kom úr sal um að félagið nýtti sér afslætti félagsskírteinis til framkvæmda þ.e.a.s. veldi fyrirtæki sem gæfu afslætti sem nýttust félaginu við slíkar framkvæmdir.",
      "Rætt var um húsakostinn, viðgerðir, vatnsveitumál og gistimöguleika.",
      "Spurt var um gömlu Djúpmannabúðina og hver ætti hana og kom í ljós að Jón Björnsson er eigangi hennar, þá var spurt um hvort ekki væri fýsilegt að fá hana til kaups aftur og var það rætt. Umræður spunnust um þá sem hefðu verið virkastir í félaginu og hverjir væru fallnir frá.",
      "Árni Jóhannsson kveður sér til hljóðs og þakkar uppgang félagsins, hann nefnir hvernig staðið er að málum í Strandamannafélaginu en þeir eiga bústað með löngum biðlista.",
      "Spurt er um Djúpmannatal og Daníel svarar því til að það er enn í höndum Ólafs Hannibalssonar en hann er að leita styrkja til útgáfu og er málið enn í vinnslu en ekki hefur verið ákveðið í hvaða formi sú útgáfa yrði. Eitthvað er til af myndum en spurning um notkunarleyfi og fleira.",
      "Umræður um ábúendur við Djúp í væntanlegum sjónvarpsþætti.",
      "Fundarstjóri þakkar fyrir sig og gefur formanni orðið.",
      "Formaður slítur fundi.",
      "Skýrsla stjórnar:",
      "Það sem hefur verið gert síðastliðið ár er eftirfarandi:",
      "Aðalfundur og vorkaffi var haldið í sal Lions.",
      "Tveir stjórnar fundir voru haldir og var þar ákveðið að koma þyrfti vatni á Álfhól og í framtíðinni á salerni við tjaldstæðið.",
      "Ákveðið var að kaupa sláttur orf til þess að slá lúpínuna í kringum Álfhól en hún hefur náð að sá sér víða í kringum húsið.",
      "Álfhóll",
      "Síðastliðið sumar var bensín sláttur orf keypt og fóru stjórnarmenn og slógu lúpínuna tvisvar.",
      "Farin var ferð vestur í djúp og bústaðurinn Álfhóll var tekinn út. Ákveðið var að Daníel,smiður og gjaldkeri félagsins myndi vera yfir framkvæmdum bústaðsins.",
      "Bústaðurinn er ekki í sem bestu ástand en ákveðið var að fara í allra nauðsynlegustu viðgerðirnar. S.s. skipta um þrjá glugga, setja upp loft túðu, mála bústaðinn að utan sem innan og setja pall í kringum hann svo hægt sé að vera þarna úti á góðum sól viðrisdögum. (sem eru ósjaldan í Mjóafirðinum)",
      "Viðræður eru í gangi við nágranna bústaðinn um það hvort að við getum tengt okkur við vatnið hjá þeim eða hvort að við getum borað okkar eigin holu þar rétt hjá. Þá munum við fá grunn vatn en ekki yfirborðsvatn.",
      "Bingo",
      "Þann 4. nóvember var haldið bingo í sal sjálfsbjargar. Mættu þar harðir bingo áhugamenn og var stemmningin góð. Og voru flottir vinningar í boði.",
      "Félagsgjöld",
      "Í fyrsta sinn í langan tíma voru félagsgjöld rukkuð með góðum undirtektum. Gjöldin eru 3000 krónur og fá þeir sem borga félagsskírteini sem mun gefa afslætti. Verið er að safna afsláttum. Ef einhver hefur áhuga á að koma hugmynd af afsláttum þá væri það vel þegið. Eins og staðan er í dag þá eru félagsmenn með afslátt hjá Flugger og Prentun.is.",
      "Bæklingur",
      "Gefinn hefur verið út bæklingur Djúpmanna í tilefni 60 ára afmælis félagsins. Vonumst við til að hann hafi gert félagið sýnilegra og minnt gamla og unga djúpmenn á að þeir séu skráðir í félagið.",
      "Spurningarkeppni átthagafélagana",
      "Við tókum þátt í spurningarkeppni átthagafélana í ár eins og í fyrra.",
      "Keppa þeir Halldór Halldórsson frá Ögri og Páll Ásgeir og Gísli Ásgeirssynir frá Þúfu þetta árið fyrir okkar hönd.",
      "Og við erum komin áfram í átta liða úrslit og verða þau 27. mars eða næstkomandi fimmtudag, klukkan 20:00 í Breiðfirðingabúð. Faxafeni 14.",
      "Beint fyrir ofan Bónus í Skeifunni. Gaman væri að sjá sem flesta Djúpmenn til að styðja við bakið á okkar mönnum.",
      "Þar að auki eru þetta bráðskemmtilegar og mjög spennandi keppnir.",
      "Á döfinni:",
      "Vorkaffi í maí",
      "Á döfinni í sumar er svo Djúpmannamót. 4. tli 6. júlí í Heydal, Mjóafirði. Það verður dansiball á laugardagskvöldinu. (Gaman væri að fá einhverjar hugmyndir um hvað er hægt að gera á laugardeginum eða jafnvel á föstudagskvöldinu) Hugmyndir eru um að leigja samkomutjald.",
      "Er svo planið að halda Djúpmannamót fjórða hvert ár í frábæra Djúpinu okkar."
    ]
  },
  {
    "id": 44,
    "slug": "stjornarfundur-2013-07-23",
    "title": "Stjórnarfundur 23.07.13",
    "dateISO": "2013-07-23",
    "paragraphs": [
      "Fundargerð stjórnarfundar 23. Júlí 2013",
      "Mættir eru Dagný Rós Stefánsdóttir, Daníel Helgason og Jórunn Silla Geirsdóttir.",
      "Fundarritari Dagný Rós Stefánsdóttir.",
      "-Formaður kom með hugmynd um að gefa út Djúpmanna bækling í janúar í tilefni 60ára afmæli félagsins. Þar væri hægt að hafa ýmislegt skemmtilegt t.d. um viðburði sem ættu að vera á því ára t.d. Djúpmannamót.",
      "Aðrir stjórnarmenn tóku vel í þá hugmynd og var ákveðið að gefa út bækling. Vantar þá sjálfboðaliða til að koma með efni í hann og til að setja hann upp. Kom upp hugmynd um hvort að hægt væri að fá auglýsingu í bæklinginn til að standast straum af kostnaði, verður það að ráðast hvort að það sé hægt.",
      "-Búið er að taka út í mjög stórum dráttum hvað þarf nauðsynlega að gera við efri bústaðinn á Galtahrygg til þess að hægt sé að leigja hann út.",
      "-Bústaður á Galtahryggnum: Rætt var um að það yrði í forgang að koma vatni á bústaðinn og ætlar Daníel að hafa samband við Atla Pálmason í sambandi við að fá afnot af borholu sem hann er með. Hugmynd er að leggja um 250m slöngu yfir í efri bústaðinn á Galtahryggnum frá borholunni til að fá vatn.",
      "-Ákveðið var að Jórunn Silla myndi taka að sér að hafa samband við bankann upp á að geta rukkað inn félagsgjöld. Einnig var ákveðið að rukkað yrði í gegnum netbanka nema að óskað yrði eftir einhverju öðru.",
      "-Haldið verður Bingo í haust með vöfflum og tilheyrandi.",
      "- Hugmynd kom inn um að safna inn afsláttum frá hinum ýmsu fyrirtækum tengdum og ótengdum djúpinu sem félagsmenn gætu síðan nýtt sér. Verður það þá gert fyrir næsta ár 2014.",
      "-Einnig kom inn hugmynd um að gefa út félagsskírteini fyrir þá félagsmenn sem hafa borgað sem þeir geta þá sýnt þegar þeir ætla að nýta sér afslættina."
    ],
    "image": "/articles/stjornarfundur-2013.jpg"
  },
  {
    "id": 40,
    "slug": "adalfundur-2013",
    "title": "Aðalfundur 2013",
    "dateISO": "2013-05-26",
    "paragraphs": [
      "Sælir góðir félagsmenn",
      "aðalfundur fyrir árið 2013 var haldinn í sal Lions, Sóltúni 20 þann 25. apríl og var mæting með ágætum. Eftir fundinn var boðið til kaffihófs með hlaðborði og fólk gat spallað og haft gaman af. Leifur Halldórsson tilkynnti að hann léti af störfum sem stjórnarmaður og formaður og þökkum við honum fyrir gott starf. Í hans stað var ákveðið að Jórunn Silla Geirsdóttir myndi taka við formansstöðu félagsins. Einnig kom Dagný Rós Stefánsdóttir ný inn í stjórn.",
      "Stjórn félagsins árið 2013 skipa því eftirtaldir:",
      "Jórunn Silla Geirsdóttir – formaður",
      "Hjörtur Aðalsteinsson",
      "Einar Kjartansson",
      "Daníel Helgason",
      "Dagný Rós Stefánsdóttir",
      "Kom upp umræða um að gera upp annað húsið sem félagið á og gera leiguhæft. Húsið er staðsett á Galtahrygg og er það mjög í niðurnýðslu í dag. Samþykkt var á fundinum að gera það upp. Samróma ákvörðun var tekin á fundinum um að taka upp félagsgjöld 3000 kr. á ári frá og með árinu 2013. Stærsta verkefni félagsins síðustu ár er ritun Djúpmannatals, en það verk hefur verið í höndum Ólafs Hannibalssonar og hefur hann unnið gott starf. Verkið er nú komið á það stig að hægt er að fara að setja það upp í tölvu til útgáfu, hvort sem það verður á rafrænu formi eða á pappír.",
      "Einnig var samþykkt að halda Djúpmannamót á næsta ári 2014, þar sem við ætlum að efla samstarfið hjá félaginu og kynna yngri félagsmenn fyrir Djúpinu góða. Einnig mun félagið verða 60 ára á næsta ári svo þetta verður stórt ár fyrir félagið.",
      "Viljum við ávalt hvetja ykkur til að láta orðróm ganga um félagið. Allir áhugamenn djúpsins eru auðvitað ávalt velkomnir í félagið.",
      "Takið strax frá fyrstu helgina í júlí sumarið 2014.",
      "Bestu kveðjur Jórunn Silla J"
    ]
  },
  {
    "id": 35,
    "slug": "adalfundur-og-vorkaffi-2013",
    "title": "Aðalfundur og vorkaffi Félags Djúpmanna",
    "dateISO": "2013-04-16",
    "paragraphs": [
      "Aðalfundur Félags Djúpmanna fyrir árið 2012 verður haldinn sumardaginn fyrsta þann 25 april kl 14.00 í sal Lions að Sóltúni 20, Reykjavík. Djúpmannafélagið býður félagsmönnum upp á kaffi með tilheyrandi á sumardaginn fyrsta",
      "Kæru félgsmenn, mætum á aðalfund og fögnum sumarkomunni.",
      "Dagskrá fundarins verður eftirfarandi:",
      "1. Formaður setur fundinn",
      "2. Skýrsla stjórnar",
      "3. Ársreikningar félagsins kynntir.",
      "4. Kosning stjórnar.",
      "5. Önnur mál, umræður.",
      "Félgsmenn eindregið hvattir til að mæta."
    ]
  },
  {
    "id": 19,
    "slug": "adalfundur-2011",
    "title": "Aðalfundur 2011",
    "dateISO": "2011-12-13",
    "paragraphs": [
      "Aðalfundur Félags Djúpmanna fyrir árið 2011 verður haldinn þann 10 janúar 2012 kl.20:00 í sal Lions að Sóltúni 20, Reykjavík.",
      "Í 5.gr. laga Félags Djúpmanna kemur fram að aðalfund skuli halda á hverju ári fyrir 15 mars.",
      "Dagskrá fundarins verður eftirfarandi:",
      "1. Formaður setur fundinn.",
      "2. Skýrsla stjórnar",
      "3. Ársreikningar félagsins.",
      "4. Kosning stjórnar.",
      "5. Kosning í nefndir.",
      "5. Önnur mál, umræður.",
      "Félagsmenn eindregið hvattir til að mæta."
    ]
  },
  {
    "id": 18,
    "slug": "skraning-i-felag-djupmanna",
    "title": "Skráning í Félag Djúpmanna",
    "dateISO": "2011-12-06",
    "paragraphs": [
      "Búið er að senda öllum skráðum félögum bréf með notendanafni og lykilorði þar sem viðkomandi er beðinn um að uppfæra inn á lokuðu svæði á heimasíðunni, allar upplýsingar um sjálfan sig og staðfesta þar með veru sína í félaginu ásamt því að setja inn upplýsingar um tengsl sín við Djúpið. Þetta er gert með því að smella á hnappinn \"innskráning\". Þá er einnig hægt að nýskrá félaga með því að fara í hnappinn \"nýskráning\" efst hægra meginn á síðunni. Ekkert félagsgjald er eða ársgjald í Félag Djúpmanna.",
      "Vinsamlegast hafði samband við einhvern af stjórnarmönnum ef þessir möguleikar virka ekki eða og við munum reyna að aðstoða við úrlausn. Einnig er möguleiki að ekki allir skráðir félagar hafi fengið bréfið í hendur og er þá bent á að hafa samband við okkur hið fyrsta og það mun verða bætt úr því."
    ]
  },
  {
    "id": 41,
    "slug": "bjorkvold-bar-11",
    "title": "Bjórkvöld Djúpmannafélagsins á BAR 11, föstudagskvöldið 20. apríl",
    "dateISO": "2011-03-20",
    "paragraphs": [
      "Bjórkvöld Djúpmannafélagsins verður haldið að BAR 11 Hverfisgötu 18 - 101 Reykjavík, föstudagskvöldið 20. apríl næstkomandi. Húsið opnar kl. 20:00 en bjórkvöldið hefst með formlegri setningu kl. 20:30.",
      "Við verðum aðeins útaf fyrir okkur framan af kvöldi en svo verður opnað fyrir almenna gesti staðarins þegar líður á.",
      "Við hvetjum alla til að koma og endurnýja kynnin við fyrrum sveitunga sína.",
      "Sjá leiðbeiningar á korti hérna!"
    ]
  },
  {
    "id": 42,
    "slug": "adalfundur-2010",
    "title": "Aðalfundur 2010",
    "dateISO": "2010-10-29",
    "paragraphs": [
      "28. október 2010 var haldin aðalfundur eftir margra ára hlé. Á þessum fundi var kosið til nýrrar stjórnar í fimm manna stjórn félagsins. Kosnir voru þeir Leifur Halldórsson frá Ögri sem var jafnframt kjörinn formaður og Daníel Helgason, frá Odda í Ögurvík er gjaldkeri. Fyrir í stjórn og sitja áfram voru þeir Einar Kjartansson, Hjörtur Aðalsteinsson og Theódór Halldórsson. Þeir sem viku úr stjórn eru Kristinn Halldórsson,fráfarandi formaður og Ólafur Hannibalsson. Þeim eru færðar hér með bestu þakkir fyrir vel unnin störf og vonandi að félagið fái að njóta starfskrafta þeirra áfram í ýmsum verkefnum sem eru framundan.",
      "Ný stjórn fundaði strax í vikunni á eftir og skipti með sér verkum og lagði línurnar m.a. um það sem þótti vera helst til þess fallið að fjölga virkum félögum, en það væri heimasíða, það að félagið sé sýnilegt á veraldarvefnum. Í þeim efnum má nefna að félagið verður samhliða heimasíðunni með síðu á samskiptavefnum Facebook eða Fésbókinni þannig að sem flestir verði okkar varir og geti fundið eitthvað við sitt hæfi."
    ]
  },
  {
    "id": 43,
    "slug": "djupmannatal-2010",
    "title": "Djúpmannatal",
    "dateISO": "2010-10-26",
    "paragraphs": [
      "Rétt er að nefna hér stórt verkefni sem félagið hefur verið með í vinnslu í nokkurn tíma en það er ættfræðigrunnur Djúpmanna, Djúpmannatal sem Ólafur Hannibalsson hefur haft veg og vanda af en spannar um 50 ára sögu hjá félaginu þannig að margir hafa komið að þeirri vinnu. Þetta verður mikið rit en ekki hefur verið tekin ákvörðun um hvernig útgáfu þess verður háttað. Lesa má samantekt Ólafs um þetta verkefni undir \"Fróðleikur\" hér á heimasíðunni."
    ]
  }
];
